language: node_js
node_js: stable
before_install:
- export TRAVIS_COMMIT_MSG="$(git log --format='%h - %B' --no-merges -n 1)"
install:
- npm install
after_success:
- sh deploy-ci.sh
branches:
 only:
  - master
  - /^tag-.*$/